bases:
  - ../base
namePrefix: eclipse-temurin-20-2000m-8g-
commonLabels:
  java: eclipse-temurin-20-2000m-8g
patchesStrategicMerge:
  - |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: java
    spec:
      containers:
        - name: java
          image: eclipse-temurin:20
          resources:
            limits:
              cpu: 2000m
              memory: 8Gi
            requests:
              cpu: 2000m
              memory: 8Gi
