bases:
  - ../base
namePrefix: eclipse-temurin-20-500m-1g-
commonLabels:
  java: eclipse-temurin-20-500m-1g
patchesStrategicMerge:
  - |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: java
    spec:
      containers:
        - name: java
          image: eclipse-temurin:20
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi
