bases:
  - ../base
namePrefix: eclipse-temurin-17-250m-512m-
commonLabels:
  java: eclipse-temurin-17-250m-512m
patchesStrategicMerge:
  - |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: java
    spec:
      containers:
        - name: java
          image: eclipse-temurin:17
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
