bases:
  - ../base
namePrefix: eclipse-temurin-20-1024m-2g-
commonLabels:
  java: eclipse-temurin-20-1000m-2g
patchesStrategicMerge:
  - |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: java
    spec:
      containers:
        - name: java
          image: eclipse-temurin:20
          resources:
            limits:
              cpu: 1024m
              memory: 2Gi
            requests:
              cpu: 1024m
              memory: 2Gi
