resources:
  - java.yaml
configMapGenerator:
  - name: main
    files:
      - Main.java
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: dockerhub-registry-secret
