bases:
  - ../base
namePrefix: eclipse-temurin-11-100m-500m-
commonLabels:
  java: eclipse-temurin-11-100m-500m
patchesStrategicMerge:
  - |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: java
    spec:
      containers:
        - name: java
          image: eclipse-temurin:11
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
